# Site settings
title: Beth Crane
name: Beth Crane
email: hello@bethcrane.com
description: Software Engineer. Photographer. Human. Excavating future!Beth, in real time.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bethcrane.com" # the base hostname & protocol for your site
github_username:  abethcrane
permalink: /:year/:month/:day/:title/
timezone: America/Los_Angeles
future: true
nav_pages:
  About: /about
  Photography: /photos
  Resume: /resume
  Posts: /posts
home_images: [becool, garden, miffy, tree, whitesands, bike]
category_tags:
  Software: [Algorithms, FoodBank, Unity, Work, Graphics, Conference, Web]
  Thoughts on Books: [Communication]
  Adventures: [Seattle, Travel]
  Projects: [FibSeq, Photography, Art, Plants]
  Private: [Gratitude, Diary]
category_blurbs:
  Software: "If this is the closest to 'be a wizard' I'm going to get, I suppose I should post some code snippets and project updates ğŸ‘©â€ğŸ’»"
  Thoughts on Books: "A few words about the many words that I've read ğŸ“š"
  Adventures: "Thoughts, stories, and photos from trips big and small ğŸ’âœˆï¸" 
  Projects: "So what do you do in your free time? ğŸ¤”"
  Private: "None of your business, actually ğŸ˜‰, but I happen to think rose-tinted glasses look good on me ğŸ•¶ï¸"
highlighter: rouge
# Build settings
markdown: kramdown
# Exclude the following from the Jekyll build process.
# Note: "vendor" is for Travis CI.
exclude: [vendor, "Gemfile", "Gemfile.lock"]
plugins: 
  - jekyll-aspect-ratio
